#!/bin/bash

mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
update-binfmts --enable qemu-arm >/dev/null 2>&1 || true

export GOPATH=/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

cp /etc/resolv.conf /armhf/etc/resolv.conf
mount -t proc none /armhf/proc
mount -t sysfs none /armhf/sys
mount -o bind /dev /armhf/dev
mount -o bind /dev/pts /armhf/dev/pts

exec "$@"