#!/bin/bash

groupadd -r builder
useradd -r -g builder builder
adduser builder sudo
mkdir -p /home/builder/go

sudo click chroot -aarmhf -fubuntu-sdk-14.04 -s trusty create

sudo click chroot -aarmhf -fubuntu-sdk-14.04 -s trusty maint apt-get install -y golang-go golang-go-linux-arm golang-go-dbus-dev golang-go-xdg-dev golang-gocheck-dev golang-gosqlite-dev libgcrypt11-dev:armhf libglib2.0-dev:armhf libwhoopsie-dev:armhf libubuntuoneauth-2.0-dev:armhf libdbus-1-dev:armhf libnih-dbus-dev:armhf libsqlite3-dev:armhf crossbuild-essential-armhf

sudo sed -i 's/overlayfs/none/' /etc/schroot/chroot.d/click-ubuntu-sdk-14.04-armhf

cat /etc/schroot/chroot.d/click-ubuntu-sdk-14.04-armhf
