build:
	wget -N http://cdimage.ubuntu.com/ubuntu-core/releases/trusty/release/ubuntu-core-14.04-core-armhf.tar.gz
	wget -N http://dave.cheney.net/paste/go1.4.2.linux-arm~multiarch-armv7-1.tar.gz
	wget -N https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
	docker build -t ninjasphere-developer .
